const mongoose = require('mongoose')
const { Schema } = mongoose

// Seed-time question bank. This is ONLY an offline fallback for "questions" mode
// when no Gemini key works. Live questions/quizzes are always generated by Gemini.
const questionSchema = new Schema(
  {
    role: { type: String, required: true },
    difficulty: { type: String, enum: ['easy', 'medium', 'hard'], default: 'medium' },
    prompt: { type: String, required: true },
  },
  { timestamps: true },
)

module.exports = mongoose.models.Question || mongoose.model('Question', questionSchema)
